### ISSUE TITLE
Sourceimages search rangeable querystring params

### ISSUE THREAD

**Issue by mweibel** [rokka-io/rokka-go#32]
[Searching sourceimages](https://rokka.io/documentation/references/searching-images.html) can be done on various fields in various ways. How we currently implement it is that you can pass a string for each of those values and define on your own whether you want to use a range or just a value.
This is not very typesafe and could be made easier by the library. Question is: is it worth the effort?
An example of how we could implement that for the string type (untested code):
```golang
type MaybeRangedString struct {
	Val string
	Range RangedString
}

func (mrs *MaybeRangedString) EncodeValues(key string, v *url.Values) error {
	if mrs.Val != "" {
		v.Set(key, mrs.Val)
		return nil
	} else {
		return mrs.Range.Encode(key, v)
	}
}

// RangedString is a string with from and to values.
// FromExclusive/ToExclusive define how the query string range is passed.
//
// From needs to be set always.
type RangedString struct {
	From          string
	To            string
	FromExclusive bool
	ToExclusive   bool
}

// EncodeValues implements query.Encoder for custom range encoding.
func (rs *RangedString) EncodeValues(key string, v *url.Values) error {
	s := ""
	if rs.FromExclusive {
		s += "{"
	} else {
		s += "["
	}
	s += rs.From
	if rs.To != "" {
		s += "," + rs.To
	}
	if rs.ToExclusive {
		s += "}"
	} else {
		s += "]"
	}
	v.Set(key, s)

	return nil
}
```

Similar implementations would have to be provided for the other types, though some things can probably be reused accross the types.

Opinions?

**Comment by pstadler** [comment]
We should check how these characters (especially `{`) are evaluated by the shell. Might requires escaping or quoting.

**Comment by mweibel** [comment]
true. Though the EncodeValues would only be used for passing that to the API. How we handle it in the CLI is another question. Benefit of these types would be that if you use the API you could construct the calls in an easier way. In #31 I moved also from simple `map[string]string` to actual structs for the querystring params.

**Comment by mweibel** [comment]
Not worth the effort at the moment. Closing until later.
