### ISSUE TITLE
Implement copying of images between organizations

### ISSUE THREAD

**Issue by mweibel** [rokka-io/rokka-go#41]

**Comment by chregu** [comment]
The cli should provide an option to copy an image or a whole organization to another one.
Currently, the API doesn't provide any functionality to avoid downloading and uploading again all the images, but a COPY operation of single images is in the backlog. Syncing of whole organizations on the server side isn't currently planned, the CLI should implement this.

One thing to consider: What should happen, if the image already exists on the target organization? Especially the meta data. Overwrite? Merge? Leave it?
