### ISSUE TITLE
Add direct link to download latest release binary

### ISSUE THREAD

**Issue by mweibel** [rokka-io/rokka-go#52]
- [x] contact GitHub to request that feature.
- [ ] rename download binaries to something user friendly.
- [ ] put download link on readme
- [ ] put binaries in ZIP archive and `chmod +x` the binary

**Comment by chregu** [comment]
you can use some rokka s3 bucket to make them available? Or does github provide such a thing as well?

**Comment by mweibel** [comment]
Yeah they are hosted on GitHub, but you can only link to the latest release (https://github.com/rokka-io/rokka-go/releases/latest) but not to an artifact on the latest release :/ 
I searched also a bit and didn't find a way. I thought about creating a small service providing that.. if I really don't find that :/

**Comment by mweibel** [comment]
fixed using https://gitreleases.dev
